version: "2"
services:
  ushahidi:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    command: run
    volumes:
      - .tars:/tars
    links:
      - mysql
    ports:
      - 11180:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
 
